[project]
name = "coder-buddy"
version = "0.1.0"
description = "AI No Code platform. Create Web application with just a prompt"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.31.0,<1.0",
    "langchain>=0.3.27,<0.4",
    "langchain-core>=0.3.72,<0.4",
    "langchain-groq>=0.3.7,<0.4",
    "langgraph>=0.6.3,<0.7",
    "pydantic>=2.11.7,<3.0",
    "python-dotenv>=1.1.1,<2.0",
    "streamlit>=1.30.0,<2.0",
]